# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4fe6853f29274257b0bc66cdc83e6c1ebbc3502344c5acfd8992e69cdeac67753d7a77344c65e54e61ff59af4fff76c42d7a18d8bb8fc57c746908a662f4ed4c

test:
  secret_key_base: 78b0652b4bb5ee10872754f0aaf07d234c7ad1fa444294ef3f53142f6b1e0e22228768f57131cb7cd7ea99c5e5ed9d037f898cdea1aae8b0b73697a06d81a3e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
